# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f65aba495bc301e1004aca633950266f0c2f717d66b2acbd2addc487107895f13dc8a5152f466a3caf047ea7fdc1360950a21d36a0c6e040737bfa91a1537023

test:
  secret_key_base: b43d93c2b0b61770f64a9153b401bc26a88cc0ba09cc7da6b2d2a16a5e9d4cfcf7e32a873b958e360446c40c5c6741df8d2bb9bb677432be5e824cd1f6718621

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
